### ISSUE TITLE
ValueError when not selecting auto-complete options in store search form.

### ISSUE THREAD

**Issue by eelcommerceconsultants** [django-oscar/django-oscar-stores#115]
When a user inputs an address and presses enter they get a ValueError:
"ValueError at /stores/
SRID is required for all geometries."

**Comment by solarissmoke** [comment]
I'm not able to reproduce this in the sandbox that is included in this repository. It sounds like you have forgotten to provide one or more of the SRID-related [settings](https://github.com/django-oscar/django-oscar-stores#settings) that are required by this package. If that isn't the issue, feel free to reopen with more detailed steps to reproduce.
