### ISSUE TITLE
AddressNotFoundError at /dashboard/stores/create/

### ISSUE THREAD

**Issue by jayvdb** [django-oscar/django-oscar-stores#124]
When creating the first new store, we see

> The address 127.0.0.1 is not in the database.

I can create a store in /admin , and the view & edit it normally in the dashboard.

GeoIP is set up, but I havent separately verified it is working.  Likewise I havent independently verified Google or spatialite are operational.

Whatever is going on, address "127.0.0.1" is illogical.

**Comment by solarissmoke** [comment]
There's nothing illogical about 127.0.0.1 - it's just your local [loopback IP address](https://en.wikipedia.org/wiki/Localhost), which presumably means you are running this on a local development server. 

It looks like the geoip2 library raises an exception for IPs it doesn't recognise, which the view isn't catching that - which it should - so there is a bug here.

**Comment by jayvdb** [comment]
I know what 127.0.0.1 is.  But in a Dashboard for users, "address" doesnt mean IP address.

**Comment by solarissmoke** [comment]
I've removed the geoip functionality altogether - the value of pre-filling a new store's location based on IP seems rather limited.
