### ISSUE TITLE
Django returns status 500 instead of 404 in some cases

### ISSUE THREAD

**Issue by thewindwaker11** [django-oscar/django-oscar-stores#146]
### Issue Summary

As described in the title, Django return 500 instead of 404 when trying to hit specific urls that do not exist.

### Steps to reproduce

Hit the following url: http://localhost:8000/en/stores/asdf/1/ , where 'asdf' can be anything and '1' can be any legal store_id.
A status 500 will appear instead of 404 since this is not an existing url.

### Technical Details

- Python: 3.5.9
- Django==2.1.5
- django-oscar==2.0.1
- django-oscar-stores==2.0
- ubuntu 20.04

### Additional Details

1. The status 500 remains when replacing 'asfd' with anything.
2. Django returns 404 when replacing 'asdf' with nothing. i.e  http://localhost:8000/en/stores/1/
3. Django returns 404 when replacing store_id with some non existent.
4. Django returns 404 in any other case.

### Quick fix
I exclude the following block of code to be returned in the urlpatterns.

```
url(r'^(?P<dummyslug>[\w-]+)/(?P<pk>\d+)/$',
                self.detail_view.as_view(), name='detail'),
```
I know this is not a permanent solution to the problem. 
From my experience, I guess, it has something to do with the 'detail_view' above.

### Traceback
https://dpaste.com/6W34EMQG5.txt

**Comment by solarissmoke** [comment]
I can't reproduce this on the sandbox site that is in this repository (I get a 404 as I would expect). The stack trace you've shared also does not suggested that this is coming from this package - it is a template syntax error which is presumably coming from a custom 404 error template. Do you have a custom 404 template, and if so what is in it?

**Comment by thewindwaker11** [comment]
Hello and thanks for the quick response, 

I tried to reproduce it in a new project and surprisingly, it returns 200. But if you look at the url code above, it makes sense to return 200 since the <dummyslug> in the url accepts any letter.
I have custom 404 and 500 templates, that extend the base.html with just a block content with a custom message.
Also, the 404 template contains the following:
```
{% block page_id %}not-found{% endblock page_id %}
```
and
```
{% block page_id %}server-error{% endblock page_id %}
```  
in the 500 template respectively.

**Comment by thewindwaker11** [comment]
It seems like it has nothing to do with oscar-stores nor django-oscar so I close this issue. Thanks for the response!
