### ISSUE TITLE
Setting SPATIALITE_LIBRARY_PATH in sandbox/settings.py causes problems in Ubuntu

### ISSUE THREAD

**Issue by elbaschid** [django-oscar/django-oscar-stores#19]
It seems that setting ``SPATIALITE_LIBRARY_PATH`` in the sandbox settings [1] file causes problems for me when trying to run the sandbox. It overrides my local setup and breaks. 

Is it possible to remove this from the settings file? Is it just the ``SPATIALITE_LIBRARY_PATH`` that needs to be set for you to get it to work? You could move that into the ``postactivate`` script of the virtualenv for the project. Would that work?

[1] [Line 212 in ``sandbox/sandbox/settings.py``](https://github.com/tangentlabs/django-oscar-stores/blob/master/sandbox/sandbox/settings.py#L212)

**Comment by codeinthehole** [comment]
Stale, closing
