### ISSUE TITLE
Does not work with Python3.3

### ISSUE THREAD

**Issue by gojesandeep** [django-oscar/django-oscar-stores#76]
I am attaching the debug panel info

Request Method:	GET
Request URL:	http://127.0.0.1:8000/dashboard/stores/create/
Django Version:	1.7.1
Exception Type:	NameError
Exception Value:	
global name 'unicode' is not defined
Exception Location:	/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/stores/dashboard/forms.py in get_weekday_display, line 140
Python Executable:	/Users/sandeepgoje/.virtualenvs/kirana3/bin/python
Python Version:	3.3.6
Python Path:	
['/Users/sandeepgoje/Work/kirana/kirana/django-oscar/sites/demo',
 '/Users/sandeepgoje/Work/kirana/kirana/django-oscar',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/django_tables2-0.15.0-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/factory_boy-2.4.1-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/mock-1.0.1-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/phonenumbers-6.3.0-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/purl-1.0.3-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/Unidecode-0.04.17-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/django_compressor-1.4-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/Babel-1.3-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/sorl_thumbnail-11.12.1b-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/django_treebeard-2.0-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/django_haystack-2.3.1-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/django_extra_views-0.6.4-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/Pillow-2.4.0-py3.3-macosx-10.10-x86_64.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/django_appconf-0.6-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/pytz-2014.10-py3.3.egg',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python33.zip',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/plat-darwin',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/lib-dynload',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/plat-darwin',
 '/Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages']

Error during template rendering

In template /Users/sandeepgoje/.virtualenvs/kirana3/lib/python3.3/site-packages/stores/templates/stores/dashboard/store_update.html, error at line 134
global name 'unicode' is not defined
124	            {% for formset in workhours %}
125	            {% if formset.non_field_errors %}
126	                {% for error in formset.non_field_errors %}
127	                    <div class="alert alert-error control-group error">
128	                        <span class="help-inline"><i class="icon-exclamation-sign"></i> {{ error }}</span>
129	                    </div>
130	                {% endfor %}
131	            {% endif %}
132	            <div class="weekday-block well">
133	                <div class="span2">
134	                  <label>{{ formset.get_weekday_display }}</label>
135	                </div>
136	
137	                <div class="span1">
138	                    <label>{{ formset.open.label }}</label>
139	                    {{ formset.open }}
140	                </div>
141	
142	                <div class="span8">
143	
144	                  <div class="row"></div>

**Comment by codeinthehole** [comment]
You're right - this package hasn't been modified to support Python 3 yet. Your stracktrace will be useful when we get around to that. Pull requests welcome of course...

**Comment by mvantellingen** [comment]
Should be fixed on the master branch now
