### ISSUE TITLE
add a tag to the current version in the master branch.

### ISSUE THREAD

**Issue by shinhermit** [django-oscar/django-oscar-stores#80]
The last commit on the master dates back to May 2015 but yet the branch has no tag that could be used for instance in a **requirements.txt** file. @NzhinuSoft [forked the project](https://github.com/NzhinuSoft/django-oscar-stores/releases/tag/0.8) to add a tag, but it would be nice if you could add this tag on the current master branch. Thanks in advance.

**Comment by solarissmoke** [comment]
Closing as we'll cut a new release shortly.
