### ISSUE TITLE
Error in documentation on url portion

### ISSUE THREAD

**Issue by b4isty** [django-oscar/django-oscar-stores#96]
URL for javascript internationalization has missing url function.
Now it's
`(r'^jsi18n/$', JavaScriptCatalog.as_view(), name="javascript-catalogue"),
`

It will be
`url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name="javascript-catalogue"),`

**Comment by solarissmoke** [comment]
Thanks! Closed in #97.
